### PR TITLE
fixed style issue #16

### PR DESCRIPTION
**Pull request by PraveenPal4232**
Hi @housseindjirdeh
please check this I just solved this "Framework pages style issue #16".

Thanks

### CODE REVIEW

**Comment by housseindjirdeh** [comment]
Thanks for this @PraveenPal4232!

There's the small issue of larger screen sizes, where an "auto" height doesn't fill out the page:

Screen Shot 2020-07-13 at 1 58 26 PM

We may have to use a combination of `min-height: 100%` and then ensure the inner containers + grid items fit the size of the screen.

**Comment by PraveenPal4232** [comment]
Oh my bad, let me fix this

**Comment by PraveenPal4232** [comment]
Hi @housseindjirdeh
Let's have a look again, now it is looking fine.

Thanks

**Review by housseindjirdeh — APPROVED** [review]

**Comment by PraveenPal4232** [comment]
Thanks, @housseindjirdeh for merging my PR :)

**Pull request merged**
